# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created: Mon Feb  5 20:55:04 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(780, 471)
        Widget.setMinimumSize(QtCore.QSize(0, 259))
        font = QtGui.QFont()
        font.setPointSize(16)
        Widget.setFont(font)
        Widget.setMouseTracking(True)
        self.gridLayout = QtWidgets.QGridLayout(Widget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Widget)
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabControl = QtWidgets.QWidget()
        self.tabControl.setMouseTracking(True)
        self.tabControl.setObjectName("tabControl")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabControl)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setContentsMargins(10, -1, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.kitDimButton = QtWidgets.QPushButton(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kitDimButton.sizePolicy().hasHeightForWidth())
        self.kitDimButton.setSizePolicy(sizePolicy)
        self.kitDimButton.setObjectName("kitDimButton")
        self.gridLayout_2.addWidget(self.kitDimButton, 2, 2, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMouseTracking(True)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 6, 10, 1)
        self.kitOnButton = QtWidgets.QPushButton(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kitOnButton.sizePolicy().hasHeightForWidth())
        self.kitOnButton.setSizePolicy(sizePolicy)
        self.kitOnButton.setObjectName("kitOnButton")
        self.gridLayout_2.addWidget(self.kitOnButton, 1, 2, 1, 1)
        self.downOffButton = QtWidgets.QPushButton(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downOffButton.sizePolicy().hasHeightForWidth())
        self.downOffButton.setSizePolicy(sizePolicy)
        self.downOffButton.setObjectName("downOffButton")
        self.gridLayout_2.addWidget(self.downOffButton, 3, 1, 1, 1)
        self.downDimButton = QtWidgets.QPushButton(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downDimButton.sizePolicy().hasHeightForWidth())
        self.downDimButton.setSizePolicy(sizePolicy)
        self.downDimButton.setObjectName("downDimButton")
        self.gridLayout_2.addWidget(self.downDimButton, 2, 1, 1, 1)
        self.downOnButton = QtWidgets.QPushButton(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downOnButton.sizePolicy().hasHeightForWidth())
        self.downOnButton.setSizePolicy(sizePolicy)
        self.downOnButton.setObjectName("downOnButton")
        self.gridLayout_2.addWidget(self.downOnButton, 1, 1, 1, 1)
        self.hallOnButton = QtWidgets.QPushButton(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hallOnButton.sizePolicy().hasHeightForWidth())
        self.hallOnButton.setSizePolicy(sizePolicy)
        self.hallOnButton.setObjectName("hallOnButton")
        self.gridLayout_2.addWidget(self.hallOnButton, 1, 3, 1, 1)
        self.hallDimButton = QtWidgets.QPushButton(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hallDimButton.sizePolicy().hasHeightForWidth())
        self.hallDimButton.setSizePolicy(sizePolicy)
        self.hallDimButton.setObjectName("hallDimButton")
        self.gridLayout_2.addWidget(self.hallDimButton, 2, 3, 1, 1)
        self.kitOffButton = QtWidgets.QPushButton(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kitOffButton.sizePolicy().hasHeightForWidth())
        self.kitOffButton.setSizePolicy(sizePolicy)
        self.kitOffButton.setObjectName("kitOffButton")
        self.gridLayout_2.addWidget(self.kitOffButton, 3, 2, 1, 1)
        self.allOffButton = QtWidgets.QPushButton(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allOffButton.sizePolicy().hasHeightForWidth())
        self.allOffButton.setSizePolicy(sizePolicy)
        self.allOffButton.setMouseTracking(True)
        self.allOffButton.setObjectName("allOffButton")
        self.gridLayout_2.addWidget(self.allOffButton, 5, 1, 1, 4)
        self.outOffButton = QtWidgets.QPushButton(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outOffButton.sizePolicy().hasHeightForWidth())
        self.outOffButton.setSizePolicy(sizePolicy)
        self.outOffButton.setObjectName("outOffButton")
        self.gridLayout_2.addWidget(self.outOffButton, 2, 4, 1, 1)
        self.outOnButton = QtWidgets.QPushButton(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outOnButton.sizePolicy().hasHeightForWidth())
        self.outOnButton.setSizePolicy(sizePolicy)
        self.outOnButton.setObjectName("outOnButton")
        self.gridLayout_2.addWidget(self.outOnButton, 1, 4, 1, 1)
        self.upOffButton = QtWidgets.QPushButton(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upOffButton.sizePolicy().hasHeightForWidth())
        self.upOffButton.setSizePolicy(sizePolicy)
        self.upOffButton.setObjectName("upOffButton")
        self.gridLayout_2.addWidget(self.upOffButton, 3, 4, 1, 1)
        self.tabWidget.addTab(self.tabControl, "")
        self.tabRoom = QtWidgets.QWidget()
        self.tabRoom.setObjectName("tabRoom")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabRoom)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.roomBlueButton = QtWidgets.QPushButton(self.tabRoom)
        self.roomBlueButton.setObjectName("roomBlueButton")
        self.gridLayout_5.addWidget(self.roomBlueButton, 13, 4, 1, 1)
        self.roomRedButton = QtWidgets.QPushButton(self.tabRoom)
        self.roomRedButton.setObjectName("roomRedButton")
        self.gridLayout_5.addWidget(self.roomRedButton, 14, 4, 1, 1)
        self.room50Button = QtWidgets.QPushButton(self.tabRoom)
        self.room50Button.setObjectName("room50Button")
        self.gridLayout_5.addWidget(self.room50Button, 2, 4, 1, 1)
        self.roomDimButton = QtWidgets.QPushButton(self.tabRoom)
        self.roomDimButton.setObjectName("roomDimButton")
        self.gridLayout_5.addWidget(self.roomDimButton, 5, 4, 1, 1)
        self.room12Button = QtWidgets.QPushButton(self.tabRoom)
        self.room12Button.setObjectName("room12Button")
        self.gridLayout_5.addWidget(self.room12Button, 4, 4, 1, 1)
        self.room100Button = QtWidgets.QPushButton(self.tabRoom)
        self.room100Button.setObjectName("room100Button")
        self.gridLayout_5.addWidget(self.room100Button, 1, 4, 1, 1)
        self.room25Button = QtWidgets.QPushButton(self.tabRoom)
        self.room25Button.setObjectName("room25Button")
        self.gridLayout_5.addWidget(self.room25Button, 3, 4, 1, 1)
        self.roomOnButton = QtWidgets.QPushButton(self.tabRoom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roomOnButton.sizePolicy().hasHeightForWidth())
        self.roomOnButton.setSizePolicy(sizePolicy)
        self.roomOnButton.setObjectName("roomOnButton")
        self.gridLayout_5.addWidget(self.roomOnButton, 1, 3, 7, 1)
        self.roomSkyButton = QtWidgets.QPushButton(self.tabRoom)
        self.roomSkyButton.setObjectName("roomSkyButton")
        self.gridLayout_5.addWidget(self.roomSkyButton, 9, 4, 1, 1)
        self.roomBrightButton = QtWidgets.QPushButton(self.tabRoom)
        self.roomBrightButton.setObjectName("roomBrightButton")
        self.gridLayout_5.addWidget(self.roomBrightButton, 10, 4, 1, 1)
        self.roomNormalButton = QtWidgets.QPushButton(self.tabRoom)
        self.roomNormalButton.setObjectName("roomNormalButton")
        self.gridLayout_5.addWidget(self.roomNormalButton, 11, 4, 1, 1)
        self.roomWarmButton = QtWidgets.QPushButton(self.tabRoom)
        self.roomWarmButton.setObjectName("roomWarmButton")
        self.gridLayout_5.addWidget(self.roomWarmButton, 12, 4, 1, 1)
        self.listWidgetRoom = QtWidgets.QListWidget(self.tabRoom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetRoom.sizePolicy().hasHeightForWidth())
        self.listWidgetRoom.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.listWidgetRoom.setFont(font)
        self.listWidgetRoom.setObjectName("listWidgetRoom")
        self.gridLayout_5.addWidget(self.listWidgetRoom, 1, 0, 15, 1)
        self.roomOffButton = QtWidgets.QPushButton(self.tabRoom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roomOffButton.sizePolicy().hasHeightForWidth())
        self.roomOffButton.setSizePolicy(sizePolicy)
        self.roomOffButton.setObjectName("roomOffButton")
        self.gridLayout_5.addWidget(self.roomOffButton, 8, 3, 7, 1)
        self.roomVerticalSlider = QtWidgets.QSlider(self.tabRoom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roomVerticalSlider.sizePolicy().hasHeightForWidth())
        self.roomVerticalSlider.setSizePolicy(sizePolicy)
        self.roomVerticalSlider.setStyleSheet("QSlider::handle{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #111111, stop:1 #CCCCCC);\n"
"    border-radius: 5px;\n"
"    border-color: #000000;\n"
"\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    height: 30px;\n"
"    width: 10px;\n"
"\n"
"    margin: 5px 5px; \n"
"}\n"
"\n"
"QSlider::groove\n"
"{\n"
"    margin-top: 20px;\n"
"    margin-bottom: 20px;\n"
"    background: qlineargradient(x1:.5, y1:0, x2:.5, y2:1, stop:0 #999999, stop:1 #FFFFFF);\n"
"\n"
"}  \n"
"")
        self.roomVerticalSlider.setMinimum(0)
        self.roomVerticalSlider.setMaximum(254)
        self.roomVerticalSlider.setPageStep(30)
        self.roomVerticalSlider.setProperty("value", 254)
        self.roomVerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.roomVerticalSlider.setTickInterval(16)
        self.roomVerticalSlider.setObjectName("roomVerticalSlider")
        self.gridLayout_5.addWidget(self.roomVerticalSlider, 1, 2, 15, 1)
        self.tabWidget.addTab(self.tabRoom, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setMouseTracking(True)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ipValue = QtWidgets.QLabel(self.tab_2)
        self.ipValue.setMouseTracking(True)
        self.ipValue.setObjectName("ipValue")
        self.gridLayout_3.addWidget(self.ipValue, 0, 1, 1, 1)
        self.ipName = QtWidgets.QLabel(self.tab_2)
        self.ipName.setMouseTracking(True)
        self.ipName.setObjectName("ipName")
        self.gridLayout_3.addWidget(self.ipName, 0, 0, 1, 1)
        self.rebootButton = QtWidgets.QPushButton(self.tab_2)
        self.rebootButton.setMouseTracking(True)
        self.rebootButton.setObjectName("rebootButton")
        self.gridLayout_3.addWidget(self.rebootButton, 2, 0, 1, 1)
        self.exitButton = QtWidgets.QPushButton(self.tab_2)
        self.exitButton.setMouseTracking(True)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout_3.addWidget(self.exitButton, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setMouseTracking(True)
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.debugText = QtWidgets.QPlainTextEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.debugText.setFont(font)
        self.debugText.setMouseTracking(True)
        self.debugText.setObjectName("debugText")
        self.gridLayout_4.addWidget(self.debugText, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Widget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.kitDimButton.setText(_translate("Widget", "Kitchen\n"
"Dim"))
        self.kitOnButton.setText(_translate("Widget", "Kitchen\n"
"On"))
        self.downOffButton.setText(_translate("Widget", "Downstairs\n"
"Off"))
        self.downDimButton.setText(_translate("Widget", "Downstairs\n"
"Dim"))
        self.downOnButton.setText(_translate("Widget", "Downstairs\n"
"On"))
        self.hallOnButton.setText(_translate("Widget", "Hall\n"
"On"))
        self.hallDimButton.setText(_translate("Widget", "Hall\n"
"Dim"))
        self.kitOffButton.setText(_translate("Widget", "Kitchen\n"
"Off"))
        self.allOffButton.setText(_translate("Widget", "All Off"))
        self.outOffButton.setText(_translate("Widget", "Outside\n"
"Off"))
        self.outOnButton.setText(_translate("Widget", "Outside\n"
"On"))
        self.upOffButton.setText(_translate("Widget", "Upstairs\n"
"Off"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabControl), _translate("Widget", "Control"))
        self.roomBlueButton.setText(_translate("Widget", "Blue"))
        self.roomRedButton.setText(_translate("Widget", "Red"))
        self.room50Button.setText(_translate("Widget", "50%"))
        self.roomDimButton.setText(_translate("Widget", "Dim"))
        self.room12Button.setText(_translate("Widget", "12%"))
        self.room100Button.setText(_translate("Widget", "100%"))
        self.room25Button.setText(_translate("Widget", "25%"))
        self.roomOnButton.setText(_translate("Widget", "On"))
        self.roomSkyButton.setText(_translate("Widget", "Sky"))
        self.roomBrightButton.setText(_translate("Widget", "Bright"))
        self.roomNormalButton.setText(_translate("Widget", "Normal"))
        self.roomWarmButton.setText(_translate("Widget", "Warm"))
        self.roomOffButton.setText(_translate("Widget", "Off"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRoom), _translate("Widget", "Rooms"))
        self.ipValue.setText(_translate("Widget", "TextLabel"))
        self.ipName.setText(_translate("Widget", "IP Address"))
        self.rebootButton.setText(_translate("Widget", "Reboot"))
        self.exitButton.setText(_translate("Widget", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Widget", "System"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Widget", "Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())

