# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created: Sun Sep 10 10:44:45 2017
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(780, 471)
        Widget.setMinimumSize(QtCore.QSize(0, 259))
        font = QtGui.QFont()
        font.setPointSize(16)
        Widget.setFont(font)
        Widget.setMouseTracking(True)
        self.gridLayout = QtWidgets.QGridLayout(Widget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Widget)
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMouseTracking(True)
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMouseTracking(True)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 2, 10, 1)
        self.allOffButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allOffButton.sizePolicy().hasHeightForWidth())
        self.allOffButton.setSizePolicy(sizePolicy)
        self.allOffButton.setMouseTracking(True)
        self.allOffButton.setObjectName("allOffButton")
        self.gridLayout_2.addWidget(self.allOffButton, 8, 0, 1, 2)
        self.downOffButton = QtWidgets.QPushButton(self.tab)
        self.downOffButton.setObjectName("downOffButton")
        self.gridLayout_2.addWidget(self.downOffButton, 3, 0, 1, 1)
        self.hallOnButton = QtWidgets.QPushButton(self.tab)
        self.hallOnButton.setObjectName("hallOnButton")
        self.gridLayout_2.addWidget(self.hallOnButton, 4, 0, 1, 1)
        self.upOffButton = QtWidgets.QPushButton(self.tab)
        self.upOffButton.setObjectName("upOffButton")
        self.gridLayout_2.addWidget(self.upOffButton, 6, 0, 1, 1)
        self.downOnButton = QtWidgets.QPushButton(self.tab)
        self.downOnButton.setObjectName("downOnButton")
        self.gridLayout_2.addWidget(self.downOnButton, 1, 0, 1, 1)
        self.downDimButton = QtWidgets.QPushButton(self.tab)
        self.downDimButton.setObjectName("downDimButton")
        self.gridLayout_2.addWidget(self.downDimButton, 2, 0, 1, 1)
        self.hallDimButton = QtWidgets.QPushButton(self.tab)
        self.hallDimButton.setObjectName("hallDimButton")
        self.gridLayout_2.addWidget(self.hallDimButton, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setMouseTracking(True)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ipValue = QtWidgets.QLabel(self.tab_2)
        self.ipValue.setMouseTracking(True)
        self.ipValue.setObjectName("ipValue")
        self.gridLayout_3.addWidget(self.ipValue, 0, 1, 1, 1)
        self.ipName = QtWidgets.QLabel(self.tab_2)
        self.ipName.setMouseTracking(True)
        self.ipName.setObjectName("ipName")
        self.gridLayout_3.addWidget(self.ipName, 0, 0, 1, 1)
        self.rebootButton = QtWidgets.QPushButton(self.tab_2)
        self.rebootButton.setMouseTracking(True)
        self.rebootButton.setObjectName("rebootButton")
        self.gridLayout_3.addWidget(self.rebootButton, 2, 0, 1, 1)
        self.exitButton = QtWidgets.QPushButton(self.tab_2)
        self.exitButton.setMouseTracking(True)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout_3.addWidget(self.exitButton, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setMouseTracking(True)
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.debugText = QtWidgets.QPlainTextEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.debugText.setFont(font)
        self.debugText.setMouseTracking(True)
        self.debugText.setObjectName("debugText")
        self.gridLayout_4.addWidget(self.debugText, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Widget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.allOffButton.setText(_translate("Widget", "All Off"))
        self.downOffButton.setText(_translate("Widget", "Downstairs Off"))
        self.hallOnButton.setText(_translate("Widget", "Hall On"))
        self.upOffButton.setText(_translate("Widget", "Upstairs Off"))
        self.downOnButton.setText(_translate("Widget", "Downstairs On"))
        self.downDimButton.setText(_translate("Widget", "Downstairs Dim"))
        self.hallDimButton.setText(_translate("Widget", "Hall Dim"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Widget", "Control"))
        self.ipValue.setText(_translate("Widget", "TextLabel"))
        self.ipName.setText(_translate("Widget", "IP Address"))
        self.rebootButton.setText(_translate("Widget", "Reboot"))
        self.exitButton.setText(_translate("Widget", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Widget", "System"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Widget", "Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())

